### ISSUE TITLE
Kinda hard to read your name in the footer

### ISSUE THREAD

**Issue by anschwa** [dylan-snyder/dylan-snyder.github.io#1]
![Screenshot](https://user-images.githubusercontent.com/6307325/140971444-e1cfb6dd-4216-4187-8ced-9b5ad8f04d4d.png)

**Comment by dylan-snyder** [comment]
Congratulations. ASSIGNED! 😎

**Comment by oneamanish** [comment]
see my pull req.

**Comment by dylan-snyder** [comment]
Hi @oneamanish, my apologies for not merging @anschwa's PR sooner.  This issue has already been covered. Thank you!
